### ISSUE TITLE
示例代码似乎不能正确使用

### ISSUE THREAD

**Issue by MingcongBai** [yunpian/yunpian-python-sdk#3]
安装 `yunpian-sdk-python` 及其依赖 `requests` 后尝试使用 Python 2 运行 README.md 中的示例代码出错如下：

```
root [ / ] # python2 test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from lib.DES import DES
ImportError: No module named lib.DES
```

观察文件前部：

```
root [ / ] ! cat test.py
# -*- coding:utf-8 -*-
# filename:TestPost
#16/1/20 下午4:01
from lib.DES import DES

__author__ = 'bingone'
from lib.SmsOperator import SmsOperator
from lib.VoiceOperator import VoiceOperator
from lib.TplOperator import TplOperator
from lib.UserOperator import UserOperator
from lib.FlowOperator import FlowOperator
from lib.Tea import Tea
```

此处的 import 是否正确使用？因为查看包内内容，模块是以如下结构安装的：

```
root [ / ] # dpkg -L yunpian-sdk-python | grep DES
/usr/lib/python2.7/site-packages/yunpian/DES.py
/usr/lib/python2.7/site-packages/yunpian/DES.pyc
/usr/lib/python2.7/site-packages/yunpian/DES.pyo
```

望指点……

**Comment by bingone** [comment]
去除DES引用（from lib.DES import DES）后再尝试一下，新版本升级没有更新README.md的示例

**Comment by MingcongBai** [comment]
依然不行，接下来就在报错说 `lib.SmSoperator` 不存在了。我试过把 `lib.*` 全部改成 `yunpian` 可以排除错误，但是后面又在别处出错了。

**Comment by bingone** [comment]
别处错误是什么

**Comment by MingcongBai** [comment]
```
root [ / ] # python2 test.py
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    smsOperator = SmsOperator(APIKEY)
TypeError: 'module' object is not callable
```

**Comment by dzh** [comment]
@MingcongBai https://github.com/yunpian/yunpian-python-sdk v1.0.0 试试新版吧
